<?php

namespace generalBundle\Repository;

/**
 * consultaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class consultaRepository extends \Doctrine\ORM\EntityRepository
{
}
