index:
    path:   /general/index/{imagen}
    defaults: { _controller: generalBundle:general:index, imagen: upload_fichero.png}
    
index2:
    path:   /general/index2/{imagen}
    defaults: { _controller: generalBundle:general:index2, imagen: upload_fichero.png}
    
fileExplore:
    path: /general/form
    defaults: { _controller: generalBundle:general:form }

vinculador:
    path: /general/vinculador
    defaults: { _controller: generalBundle:general:vinculador }
    
picture:
    path: /general/vinculador/{imagen}
    defaults: { _controller: generalBundle:general:picture , imagen: upload_fichero.png }
    
formulariobusqueda:
    path: /general/formulariobusqueda
    defaults: { _controller: generalBundle:general:formulariobusqueda }
    
busqueda:
    path: /general/busqueda
    defaults: { _controller: generalBundle:general:busqueda }
 
conocenos:
    path: /general/conocenos
    defaults: { _controller: generalBundle:general:conocenos }
    
llamada:
    path:   /general/llamada
    defaults: { _controller: generalBundle:general:llamada }