index:
    path:   /general/index
    defaults: { _controller: generalBundle:general:index }
    
fileExplore:
    path: /general/form
    defaults: { _controller: generalBundle:general:form }
    
vinculador:
    path: /general/vinculador
    defaults: { _controller: generalBundle:general:vinculador }
    
picture:
    path: /general/vinculador
    defaults: { _controller: generalBundle:general:picture }